version: '3.5'

networks:
  bugloos:

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/sites/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs/nginx:/var/log/nginx
    restart: unless-stopped
    depends_on:
      - app
      - mysql
    networks:
      - bugloos

  mysql:
    image: mysql:8.0.21
    container_name: mysql
    command: ['--default-authentication-plugin=mysql_native_password']
    restart: unless-stopped
    tty: true
    ports:
      - 33060:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: bugloos
      MYSQL_USER: root
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    networks:
      - bugloos

  app:
    build:
      context: ./docker/php-fpm
    container_name: app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    ports:
      - 9000:9000
    networks:
      - bugloos

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    volumes:
      - ./docker/redis/data:/data
    ports:
      - 6379:6379
    networks:
      - bugloos

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - 8585:80
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - bugloos
